# Makefile for an A2F-Linux project

# This project's name
SAMPLE		:= DCS

# Custom applcations subdirectories that this project
# needs to build. Edit this list as appropriate for your application.
CUSTOM_APPS	:= feeserver-0.9.1-rcu-0.9.2

# Include Make rules applicable to all projects
include ../Rules.make
